service: aws-rds-snapshots
frameworkVersion: '3'
# To deploy use sls deploy --stage (source ou target) --region (set aws region)
provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: ${opt:region, 'us-east-1'} # you can overwrite defaults here
  environment:
    DATABASE_NAME_PATTERN: TAG
    BACKUP_INTERVAL: ${self:custom.backupInterval}
    SOURCE_AWS_REGION: ${self:custom.sourceAwsRegion}
    TARGET_AWS_REGION: ${self:custom.targetAwsRegion}
    AWS_TARGET_KMS_KEY: ${self:custom.awsTargetKmsKey}
    AWS_SOURCE_ACCOUNT: ${self:custom.awsTargetAccount.source}
    AWS_TARGET_ACCOUNT: ${self:custom.awsTargetAccount.target}
    LOG_LEVEL: info
    # uncomment and type the RDS identifier to debug
    #DEBUG_DATABASE: fitness-classes-production-cluster
    TZ: ${self:custom.awsTimeZone}
    SNAPSHOT_OLD_IN_DAYS: ${self:custom.backupRetention}
    INGNORE_SNAPSHOTS_TAG: ${self:custom.ignoreTag}
    PURGE_SOURCE_SNAPSHOTS: ${self:custom.purgeSourceSnaps}

# you can add statements to the Lambda function's IAM Role here
resources:
  Resources:
    sourceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AwsRdsSnapshotsSourceRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AwsRdsSnapshotsSourcePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "rds:DescribeDBInstances"
                    - "rds:DescribeDBClusters"
                    - "rds:DescribeDBClusterSnapshots"
                    - "rds:DescribeDBSnapshots"
                    - "rds:AddTagsToResource"
                    - "rds:CreateDBClusterSnapshot"
                    - "rds:CreateDBSnapshot"
                    - "rds:CopyDBClusterSnapshot"
                    - "rds:CopyDBSnapshot"
                    - "rds:ModifyDBClusterSnapshotAttribute"
                    - "rds:ModifyDBSnapshotAttribute"
                    - "rds:DeleteDBClusterSnapshot"
                    - "rds:DeleteDBSnapshot"
                    - "kms:CreateGrant"
                    - "kms:Encrypt"
                    - "kms:Decrypt"
                    - "kms:ReEncrypt*"
                    - "kms:GenerateDataKey*"
                    - "kms:DescribeKey"
                  Resource: [
                    "arn:aws:rds:*:${self:custom.awsTargetAccount.source}:db:*",
                    "arn:aws:rds:*:${self:custom.awsTargetAccount.source}:cluster:*",
                    "arn:aws:rds:*:*:cluster-snapshot:*",
                    "arn:aws:rds:*:*:snapshot:*",
                     "arn:aws:kms:*:*:key/*"
                    ]
        - PolicyName: AwsRdsSnapshotsSourcePolicyLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: '*'
    targetRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AwsRdsSnapshotsTargetRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AwsRdsSnapshotsTargetPolicy
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                    Action:
                      - "rds:DescribeDBInstances"
                      - "rds:DescribeDBClusters"
                      - "rds:DescribeDBClusterSnapshots"
                      - "rds:DescribeDBSnapshots"
                      - "rds:AddTagsToResource"
                      - "rds:CreateDBInstance"
                      - "rds:CopyDBClusterSnapshot"
                      - "rds:CopyDBSnapshot"
                      - "rds:ModifyDBCluster"
                      - "rds:ModifyDBInstance"
                      - "rds:ModifyDBClusterSnapshotAttribute"
                      - "rds:ModifyDBSnapshotAttribute"
                      - "rds:DeleteDBClusterSnapshot"
                      - "rds:DeleteDBSnapshot"
                      - "rds:RestoreDBClusterFromSnapshot"
                      - "rds:RestoreDBInstanceFromDBSnapshot"
                      - "rds:DeleteDBCluster"
                      - "rds:DeleteDBInstance"
                      - "kms:CreateGrant"
                      - "kms:Encrypt"
                      - "kms:Decrypt"
                      - "kms:ReEncrypt*"
                      - "kms:GenerateDataKey*"
                      - "kms:DescribeKey"
                    Resource: [
                      "arn:aws:rds:*:${self:custom.awsTargetAccount.target}:db:*",
                      "arn:aws:rds:*:${self:custom.awsTargetAccount.target}:cluster:*",
                      "arn:aws:rds:*:*:cluster-snapshot:*",
                      "arn:aws:rds:*:*:snapshot:*",
                      "arn:aws:rds:*:${self:custom.awsTargetAccount.target}:subgrp:*",
                      "arn:aws:kms:*:*:key/*"
                      ]
          - PolicyName: AwsRdsSnapshotsTargetPolicyLogs
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: '*'

# generate lambda for source account, (stage == source) 
functions:
  lambda_handler_source:
    role: sourceRole
    handler: copy_or_take_snapshots.lambda_handler
    timeout: 60
    events:
      - schedule: cron(0/5 * ? * * *)

# generate lambda for target account, (stage == target)
lambda_handler_target:
    role: targetRole
    handler: restore_snapshots.lambda_handler
    timeout: 60
    events:
      - schedule: cron(0/5 * ? * * *)

custom:
  pythonRequirements:
    useDownloadCache: false
    slim: true
  # Define wich git information will be exported to ENVs or TAGs in the functions
  gitVariablesEnvWhitelist: []
  gitVariablesTagsWhitelist: ['GIT_REPOSITORY', 'GIT_BRANCH']
  # Define wich functions must be deployed based on stage passes to deploy as --stage (source or target).
  serverlessIfElse:
    - If: '"${self:provider.stage}" == "source"'
      Exclude:
        - functions.lambda_handler_target
    - If: '"${self:provider.stage}" == "target"'
      Exclude:
        - functions.lambda_handler_source
  # Replace with the interval in hours
  backupInterval: 6
  # Replace value with the source region
  sourceAwsRegion: us-east-1
  # Replace value with the target region
  targetAwsRegion: us-west-2
  # Replace value with the target account KMS key name,  key ID like mrk-85733a57f8ca4964ac1c3c001b190b3f 
  # (it needs to be accessible from target account and be replicate in target region)
  awsTargetKmsKey: mrk-85733a57f8ca4964ac1c3c001b190b3f
  # Replace these values with source and target AWS account numbers
  awsTargetAccount:
    source: 222222222222
    target: 111111111111
  # Replace these values with UTC Time Zone
  awsTimeZone: Etc/GMT
  # Define snapshot retention time in days
  backupRetention: 30
  # Define manual snapshots with specific tag to ignore
  ignoreTag: None
  # Set to true to delete/purge source region snapshots after shared to the target region (works when source and target regions are different) otherwise set to false
  purgeSourceSnap: true


plugins:
  - serverless-python-requirements
  - serverless-plugin-select
  - serverless-plugin-git-variables
  - serverless-plugin-ifelse
